import { Referral } from "@/types/api";
import { addHours, subDays } from "date-fns";

export const mockPsychologistStats = {
  pending_confirmation_count: 61,
  confirmed_schedule_count: 30,
  completed_case_count: 5,
};

export const mockReferrals: Referral[] = [
  {
    id: "ref-1",
    student_name: "Alex Allan",
    priority: "Kritis",
    status: "Menunggu Konfirmasi",
    remaining_time: "18:00:00",
    date: "08/28/2025",
    time: "10:00",
    referrer_name: "Sri Wahyuni, S.Pd, M.Pd",
    counselor_notes: "Siswa menunjukkan gejala kecemasan akademik berkepanjangan dan membutuhkan asesmen lanjutan. Telah dilakukan sesi konseling awal sebanyak dua kali.",
    submitted_at: "23 Mei 2026, 14:00 WIB",
    is_expired: false,
    nis: "TRD-64851",
    class_name: "X IPA 1",
    student_story: "Saya akhir-akhir ini capek banget sama tugas sekolah dan sering kepikiran nilai jelek dan stress. Kadang jadi malas masuk kelas dan pengen sendiri dulu.",
    detected_keywords: ["stress", "cemas", "sendiri"],
    ai_summary: "Siswa melaporkan tekanan akademik yang meningkat dalam beberapa minggu terakhir, disertai kelelahan emosional, penurunan motivasi belajar, dan kecenderungan menarik diri dari lingkungan kelas. Tidak ditemukan pernyataan eksplisit terkait keinginan menyakiti diri, namun terdapat indikasi distress emosional yang memerlukan asesmen lebih lanjut.\n\nGuru BK telah melakukan sesi konseling awal dan merekomendasikan evaluasi profesional lanjutan untuk menentukan kebutuhan pendampingan psikologis yang lebih tepat. Kata-kata kunci yang terdeteksi antara lain: kelelahan emosional, isolasi sosial, dan penurunan motivasi, semua berada di bawah ambang batas kritis namun memerlukan perhatian segera.",
  },
  {
    id: "ref-2",
    student_name: "Dewi Ratnasari",
    priority: "Prioritas",
    status: "Menunggu Konfirmasi",
    remaining_time: "03:00:00",
    date: "08/28/2025",
    time: "10:00",
    referrer_name: "Sri Wahyuni, S.Pd, M.Pd",
    counselor_notes: "Siswa mengalami kesulitan berinteraksi dengan teman sebaya dan menunjukkan tanda-tanda isolasi sosial.",
    submitted_at: "22 Mei 2026, 14:00 WIB",
    is_expired: false,
    nis: "TRD-64852",
    class_name: "X IPA 2",
    student_story: "Teman-teman di kelas kayaknya pada nggak suka sama aku. Aku bingung mau ngobrol apa.",
    detected_keywords: ["sedih", "kesepian", "bingung"],
    ai_summary: "Siswa menunjukkan gejala kecemasan sosial dan kesulitan dalam membangun relasi dengan teman sebaya. Indikator utama adalah perasaan terasing dan kesulitan menginisiasi interaksi sosial.",
  },
  {
    id: "ref-3",
    student_name: "Ardi Putra",
    priority: "Kritis",
    status: "Menunggu Konfirmasi",
    remaining_time: "Kedaluarsa",
    date: "08/28/2025",
    time: "10:00",
    referrer_name: "Sri Wahyuni, S.Pd, M.Pd",
    counselor_notes: "Penurunan drastis nilai akademik disertai perubahan perilaku. Orang tua melaporkan perubahan pola tidur.",
    submitted_at: "21 Mei 2026, 14:00 WIB",
    is_expired: true,
  },
  {
    id: "ref-4",
    student_name: "Ardi Putra",
    priority: "Prioritas",
    status: "Terkonfirmasi",
    remaining_time: "-",
    date: "08/28/2025",
    time: "10:00",
    referrer_name: "Sri Wahyuni, S.Pd, M.Pd",
    counselor_notes: "Penurunan drastis nilai akademik disertai perubahan perilaku. Orang tua melaporkan perubahan pola tidur.",
    submitted_at: "21 Mei 2026, 14:00 WIB",
    is_expired: false,
  },
  {
    id: "ref-5",
    student_name: "Ardi Putra",
    priority: "Kritis",
    status: "Ditolak",
    remaining_time: "-",
    date: "08/28/2025",
    time: "10:00",
    referrer_name: "Sri Wahyuni, S.Pd, M.Pd",
    counselor_notes: "Penurunan drastis nilai akademik disertai perubahan perilaku. Orang tua melaporkan perubahan pola tidur.",
    submitted_at: "21 Mei 2026, 14:00 WIB",
    is_expired: false,
  },
  {
    id: "ref-6",
    student_name: "Ardi Putra",
    priority: "Prioritas",
    status: "Selesai",
    remaining_time: "-",
    date: "08/28/2025",
    time: "10:00",
    referrer_name: "Sri Wahyuni, S.Pd, M.Pd",
    counselor_notes: "Penurunan drastis nilai akademik disertai perubahan perilaku. Orang tua melaporkan perubahan pola tidur.",
    submitted_at: "21 Mei 2026, 14:00 WIB",
    is_expired: false,
  }
];
